name: ERC7579 Indexer
description: ERC7579 Module Indexer
contracts:
  - name: EntryPointV0_7_0
    abi_file_path: ./abis/entryPointV0_7_0.json
    handler: ./src/entryPoint.ts
    events:
      - event: AccountDeployed(bytes32 indexed userOpHash, address indexed sender, address factory, address paymaster)
networks:
  - id: 137 # Polygon
    start_block: 0
    contracts:
      - name: EntryPointV0_7_0
        address: "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
rollback_on_reorg: false
