# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Greeter
description: Greeter indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: EntryPointV0_7_0
    abi_file_path: ./abis/entryPointV0_7_0.json
    handler: ./src/entryPoint.ts
    events:
      - event: AccountDeployed(bytes32 indexed userOpHash, address indexed sender, address factory, address paymaster)
networks:
  - id: 137 # Polygon
    start_block: 0
    contracts:
      - name: EntryPointV0_7_0
        address: "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
